export const COUNTRIES = [
  { value: 1, label: "Afghanistan" },
  { value: 2, label: "Afrique du Sud" },
  { value: 3, label: "Albanie" },
  { value: 4, label: "Algérie" },
  { value: 5, label: "Allemagne" },
  { value: 6, label: "Andorre" },
  { value: 7, label: "Angola" },
  { value: 8, label: "Antigua-et-Barbuda" },
  { value: 9, label: "Arabie saoudite" },
  { value: 10, label: "Argentine" },
  { value: 11, label: "Arménie" },
  { value: 12, label: "Australie" },
  { value: 13, label: "Autriche" },
  { value: 14, label: "Azerbaïdjan" },
  { value: 15, label: "Bahamas" },
  { value: 16, label: "Bahreïn" },
  { value: 17, label: "Bangladesh" },
  { value: 18, label: "Barbade" },
  { value: 19, label: "Belgique" },
  { value: 20, label: "Belize" },
  { value: 21, label: "Bénin" },
  { value: 22, label: "Bhoutan" },
  { value: 23, label: "Biélorussie" },
  { value: 24, label: "Birmanie" },
  { value: 25, label: "Bolivie" },
  { value: 26, label: "Bosnie-Herzégovine" },
  { value: 27, label: "Botswana" },
  { value: 28, label: "Brésil" },
  { value: 29, label: "Brunei" },
  { value: 30, label: "Bulgarie" },
  { value: 31, label: "Burkina Faso" },
  { value: 32, label: "Burundi" },
  { value: 33, label: "Cambodge" },
  { value: 34, label: "Cameroun" },
  { value: 35, label: "Canada" },
  { value: 36, label: "Cap-Vert" },
  { value: 37, label: "République centrafricaine" },
  { value: 38, label: "Chili" },
  { value: 39, label: "Chine" },
  { value: 40, label: "Chypre" },
  { value: 41, label: "Colombie" },
  { value: 42, label: "Comores" },
  { value: 43, label: "République du Congo" },
  { value: 44, label: "République démocratique du Congo" },
  { value: 45, label: "îles Cook" },
  { value: 46, label: "Corée du Nord" },
  { value: 47, label: "Corée du Sud" },
  { value: 48, label: "Costa Rica" },
  { value: 49, label: "Côte d'Ivoire" },
  { value: 50, label: "Croatie" },
  { value: 51, label: "Cuba" },
  { value: 52, label: "Danemark" },
  { value: 53, label: "Djibouti" },
  { value: 54, label: "République dominicaine" },
  { value: 55, label: "Dominique" },
  { value: 56, label: "Égypte" },
  { value: 57, label: "Émirats arabes unis" },
  { value: 58, label: "Équateur" },
  { value: 59, label: "Érythrée" },
  { value: 60, label: "Espagne" },
  { value: 61, label: "Estonie" },
  { value: 62, label: "États-Unis" },
  { value: 63, label: "Éthiopie" },
  { value: 64, label: "Fvalueji" },
  { value: 65, label: "Finlande" },
  { value: 66, label: "France" },
  { value: 67, label: "Gabon" },
  { value: 68, label: "Gambie" },
  { value: 69, label: "Géorgie" },
  { value: 70, label: "Ghana" },
  { value: 71, label: "Grèce" },
  { value: 72, label: "Grenade" },
  { value: 73, label: "Guatemala" },
  { value: 74, label: "Guinée" },
  { value: 75, label: "Guinée-Bissau" },
  { value: 76, label: "Guinée équatoriale" },
  { value: 77, label: "Guyana" },
  { value: 78, label: "Haïti" },
  { value: 79, label: "Honduras" },
  { value: 80, label: "Hongrie" },
  { value: 81, label: "Inde" },
  { value: 82, label: "Indonésie" },
  { value: 83, label: "Irak" },
  { value: 84, label: "Iran" },
  { value: 85, label: "Irlande" },
  { value: 86, label: "Islande" },
  { value: 87, label: "Israël" },
  { value: 88, label: "Italie" },
  { value: 89, label: "Jamaïque" },
  { value: 90, label: "Japon" },
  { value: 91, label: "Jordanie" },
  { value: 92, label: "Kazakhstan" },
  { value: 93, label: "Kenya" },
  { value: 94, label: "Kirghizistan" },
  { value: 95, label: "Kiribati" },
  { value: 96, label: "Koweït" },
  { value: 97, label: "Laos" },
  { value: 98, label: "Lesotho" },
  { value: 99, label: "Lettonie" },
  { value: 100, label: "Liban" },
  { value: 101, label: "Liberia" },
  { value: 102, label: "Libye" },
  { value: 103, label: "Liechtenstein" },
  { value: 104, label: "Lituanie" },
  { value: 105, label: "Luxembourg" },
  { value: 106, label: "Macédoine" },
  { value: 107, label: "Madagascar" },
  { value: 108, label: "Malaisie" },
  { value: 109, label: "Malawi" },
  { value: 110, label: "Maldives" },
  { value: 111, label: "Mali" },
  { value: 112, label: "Malte" },
  { value: 113, label: "Maroc" },
  { value: 114, label: "îles Marshall" },
  { value: 115, label: "Maurice" },
  { value: 116, label: "Mauritanie" },
  { value: 117, label: "Mexique" },
  { value: 118, label: "Micronésie" },
  { value: 119, label: "Moldavie" },
  { value: 120, label: "Monaco" },
  { value: 121, label: "Mongolie" },
  { value: 122, label: "Monténégro" },
  { value: 123, label: "Mozambique" },
  { value: 124, label: "Namibie" },
  { value: 125, label: "Nauru" },
  { value: 126, label: "Népal" },
  { value: 127, label: "Nicaragua" },
  { value: 128, label: "Niger" },
  { value: 129, label: "Nigeria" },
  { value: 130, label: "Niue" },
  { value: 131, label: "Norvège" },
  { value: 132, label: "Nouvelle-Zélande" },
  { value: 133, label: "Oman" },
  { value: 134, label: "Ouganda" },
  { value: 135, label: "Ouzbékistan" },
  { value: 136, label: "Pakistan" },
  { value: 137, label: "Palaos" },
  { value: 138, label: "État de Palestine" },
  { value: 139, label: "Panamá" },
  { value: 140, label: "Papouasie-Nouvelle-Guinée" },
  { value: 141, label: "Paraguay" },
  { value: 142, label: "Pays-Bas" },
  { value: 143, label: "Pérou" },
  { value: 144, label: "Philippines" },
  { value: 145, label: "Pologne" },
  { value: 146, label: "Portugal" },
  { value: 147, label: "Qatar" },
  { value: 148, label: "Roumanie" },
  { value: 149, label: "Royaume-Uni" },
  { value: 150, label: "Russie" },
  { value: 151, label: "Rwanda" },
  { value: 152, label: "Saint-Christophe-et-Niévès" },
  { value: 153, label: "Saint-Marin" },
  { value: 154, label: "Saint-Vincent-et-les Grenadines" },
  { value: 155, label: "Sainte-Lucie" },
  { value: 156, label: "îles Salomon" },
  { value: 157, label: "Salvador" },
  { value: 158, label: "Samoa" },
  { value: 159, label: "São Tomé-et-Principe" },
  { value: 160, label: "Sénégal" },
  { value: 161, label: "Serbie" },
  { value: 162, label: "Seychelles" },
  { value: 163, label: "Sierra Leone" },
  { value: 164, label: "Singapour" },
  { value: 165, label: "Slovaquie" },
  { value: 166, label: "Slovénie" },
  { value: 167, label: "Somalie" },
  { value: 168, label: "Soudan" },
  { value: 169, label: "Soudan du Sud" },
  { value: 170, label: "Sri Lanka" },
  { value: 171, label: "Suède" },
  { value: 172, label: "Suisse" },
  { value: 173, label: "Suriname" },
  { value: 174, label: "Swaziland" },
  { value: 175, label: "Syrie" },
  { value: 176, label: "Tadjikistan" },
  { value: 177, label: "Tanzanie" },
  { value: 178, label: "Tchad" },
  { value: 179, label: "République tchèque" },
  { value: 180, label: "Thaïlande" },
  { value: 181, label: "Timor oriental" },
  { value: 182, label: "Togo" },
  { value: 183, label: "Tonga" },
  { value: 184, label: "Trinité-et-Tobago" },
  { value: 185, label: "Tunisie" },
  { value: 186, label: "Turkménistan" },
  { value: 187, label: "Turquie" },
  { value: 188, label: "Tuvalu" },
  { value: 189, label: "Ukraine" },
  { value: 190, label: "Uruguay" },
  { value: 191, label: "Vanuatu" },
  { value: 192, label: "Vatican" },
  { value: 193, label: "Venezuela" },
  { value: 194, label: "Viêt Nam" },
  { value: 195, label: "Yémen" },
  { value: 196, label: "Zambie" },
  { value: 197, label: "Zimbabwe" },
  { value: 198, label: "Abkhazie" },
  { value: 199, label: "Chypre du Nord" },
  { value: 200, label: "Hong Kong" },
  { value: 201, label: "Kosovo" },
  { value: 202, label: "Ossétie du Sud" },
  { value: 203, label: "Sahara occvalueental" },
  { value: 204, label: "Taïwan" }
];
